module.exports.config = {
  name: "gai2",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Mirai Team",
  description: "Random ảnh girl",
 Category: "random-img",
 prefix: 'awto',
 usages: "gái",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/FNRRTy7.jpg",
"https://i.imgur.com/GDEBTl2.jpg",
"https://i.imgur.com/dOZwgSd.jpg",
"https://i.imgur.com/Sh0kRwG.jpg",
"https://i.imgur.com/M0AYNug.jpg",
"https://i.imgur.com/vmU9UAM.jpg",
"https://i.imgur.com/QIcueNQ.jpg",
"https://i.imgur.com/xAU0nhF.jpg",
"https://i.imgur.com/YrfpgRK.jpg",
"https://i.imgur.com/gZzXhlI.jpg",
"https://i.imgur.com/m6pQwFY.jpg",
"https://i.imgur.com/g4VArWU.jpg",
"https://i.imgur.com/5j5OboX.jpg",
"https://i.imgur.com/DrjPCxZ.jpg",
"https://i.imgur.com/k5nG1hR.jpg",
"https://i.imgur.com/tpqGDGf.jpg",
"https://i.imgur.com/Q8VLAUw.jpg",
"https://i.imgur.com/lyPc2A8.jpg",
"https://i.imgur.com/ATOUNQL.jpg",
"https://i.imgur.com/iGzMHrV.png",
"https://i.imgur.com/jppLuim.jpg",
"https://i.imgur.com/GORiYUe.jpg",
"https://i.imgur.com/vmwkLa2.jpg",
"https://i.imgur.com/zv8RhN7.jpg",
"https://i.imgur.com/jUMfLcS.jpg",
"https://i.imgur.com/l17Ory1.jpg",
"https://i.imgur.com/DE1TKsQ.jpg",
"https://i.imgur.com/mosyDBJ.jpg",
"https://i.imgur.com/BQu1WQ8.jpg",
"https://i.imgur.com/wof8jon.jpg",
"https://i.imgur.com/IMZGA08.jpg",
"https://i.imgur.com/bW0lHwr.jpg",
"https://i.imgur.com/YdB116g.jpg",
"https://i.imgur.com/ZMQXntv.jpg",
"https://i.imgur.com/x3Zqf83.jpg",
"https://i.imgur.com/ZAzfpHm.jpg",
"https://i.imgur.com/jb0VcXf.jpg",
"https://i.imgur.com/vSnK0kM.jpg",
"https://i.imgur.com/lLe52T9.jpg",
"https://i.imgur.com/y9Obelj.jpg",
"https://i.imgur.com/W9D70jS.jpg",
"https://i.imgur.com/iakSOjj.jpg",
"https://i.imgur.com/B0LZTMK.jpg",
"https://i.imgur.com/s897YGf.jpg",
"https://i.imgur.com/jI1HEbN.jpg",
"https://i.imgur.com/aYyFibI.jpg",
"https://i.imgur.com/RJsE4Oa.jpg",
"https://i.imgur.com/TREw7IL.jpg",
"https://i.imgur.com/qoTa0Vb.jpg",
"https://i.imgur.com/N3aAEbZ.jpg",
"https://i.imgur.com/NXBaIdB.jpg",
